---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- name: project_description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Project Description
  description: describe the project here.
- name: project_image
  type: file
  config:
    maxSize: 64
  label: Project image
  description: upload an image to represent the project please.
- name: secondary_photo
  type: file
  config:
    maxSize: 64
  label: Secondary photo
  description: Visible on the project page
- name: project_type
  type: select
  default: []
  config:
    required: false
    options:
    - project
    - coding project
    source:
      type: simple
      section: 
      file: 
      path: 
  label: project type
  description: pick your project type
- name: date_range
  type: text
  config:
    required: false
  label: Date Range
  description: add the date range of the project (2011-2014) for example
pages:
- content/coding-projects/classswapper.md
- content/coding-projects/compound-interest.md
- content/coding-projects/hotdogger.md
- content/coding-projects/ui-tests.md
- content/coding-projects/vue-quiz.md
- content/projects/earthmounds.md
- content/projects/edgar-yolkman.md
- content/projects/edgewater-workbench.md
- content/projects/puzzle-truck.md
- content/projects/timelapse.md
