---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- name: project_description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Project Description
  description: describe the project here.
- name: project_image
  type: file
  config:
    maxSize: 64
  label: Project image
  description: upload an image to represent the project please.
- name: square_thumbnail
  type: file
  config:
    maxSize: 64
  label: Square thumbnail
  description: Please upload a square thumbnail preview image to represent the project
- name: project_type
  type: select
  default: []
  config:
    required: false
    options:
    - project
    - " coding project"
    source:
      type: simple
      section: 
      file: 
      path: 
  label: project type
  description: pick your project type
pages:
- content/coding-projects/vue-quiz.md
- content/projects/earthmounds.md
- content/projects/edgar-yolkman.md
- content/projects/edgewater-workbench.md
- content/projects/puzzle-truck.md
