---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- name: project_description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Project Description
  description: describe the project here.
- name: project_image
  type: file
  config:
    maxSize: 64
  label: Project image
  description: upload an image to represent the project please.
- name: square_thumbnail
  type: file
  config:
    maxSize: 64
  label: Square thumbnail
  description: Please upload a square thumbnail preview image to represent the project
pages:
- content/projects/edgar-yolkman.md
